backend:
  name: git-gateway
  branch: master
  repo: https://github.com/SandyWyper/SWWS-JulieMossFineArt

media_folder: static/uploads
public_folder: /uploads


collections:
  - name: "artwork"
    label: "Artwork"
    folder: "content/artwork"
    create: true
    slug: "{{title}}"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Details", name: "details", widget: "string", required: false  }
      - { label: "Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY" }
      - { label: "Description excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Description", name: "body", widget: "markdown", required: false }
      - { label: "Featured Artwork", name: "isFeatured", widget: "boolean", default: false }
      - { label: "Available for sale", name: "isForSale", widget: "boolean", default: false }
      - { label: "Images", name: "images", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, { label: "Image description", name: "alt", widget: "string"}] }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{title}}"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Main Image", name: "mainImage", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Image Description", name: "imageAlt", widget: "string" }]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/pages/home/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Intro", name: "intro", widget: "object", fields: [{ label: "Intro text", name: "introText", widget: "text"}, { label: "Intro image", name: "introImage", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Image description", name: "imageAlt", widget: "string" }]}]}       
      - file: "content/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Main Image", name: "mainImage", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Image description", name: "imageAlt", widget: "string" }]}
          - { label: "Body", name: "body", widget: "markdown"}
      - file: "content/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page" }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Prompt", name: "prompt", widget: "string" }
          - { label: "Image", name: "image", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Image description", name: "imageAlt", widget: "string" }]}
